### PR TITLE
Launcher for Natro

### PR DESCRIPTION
**Pull request by supercoolspy**
A launcher written in rust that allows for auto updating and auto extracting the zip file (soon)

### CODE REVIEW

**Comment by zspz** [comment]
What advantages does this provide over the .bat files?

**Comment by supercoolspy** [comment]
Auto updating functionality and the extracting while still maintaining a readable code base compared to the bat files

**Comment by zspz** [comment]
Both of these features are already present and I don't think this provides a significant readability improvement.

**Comment by supercoolspy** [comment]
> Both of these features are already present and I don't think this provides a significant readability improvement.
Do you know where the auto update is I couldn't find it when I tried searching for things calling update.bat

**Comment by supercoolspy** [comment]
The other main goal with this is to try to at some point be able to make a cross platform solution with roblox [now being able to run on linux and (probably) wsl](https://vinegarhq.org/)

**Comment by supercoolspy** [comment]
Would you prefer if I was able to make a graphical gui for installing and launching Natro? @zspz

**Comment by zspz** [comment]
> Do you know where the auto update is I couldn't find it when I tried searching for things calling update.bat

You can find it by searching `AutoUpdate` in [natro_macro.ahk](https://github.com/NatroTeam/NatroMacro/blob/80c3c659ca5115cba56755c05fbea800b3bf27f0/submacros/natro_macro.ahk#L1817).

> The other main goal with this is to try to at some point be able to make a cross platform solution with roblox [now being able to run on linux and (probably) wsl](https://vinegarhq.org/)

That would be interesting, we've only focused on Windows so far with no intention to expand, as do the AHK developers themselves. However, I still don't see this as a reason to use a Rust executable when you would require something like Wine to run AHK anyway (at which point you can just use the .bat with Wine too).

> Would you prefer if I was able to make a graphical gui for installing and launching Natro? @zspz

I think that would be nice and would definitely make the installation process easier 😃

**Comment by supercoolspy** [comment]
> You can find it by searching `AutoUpdate` in [natro_macro.ahk](https://github.com/NatroTeam/NatroMacro/blob/80c3c659ca5115cba56755c05fbea800b3bf27f0/submacros/natro_macro.ahk#L1817).

Ok, was looking for the update.bat usage so that explains it :+1: 

> That would be interesting, we've only focused on Windows so far with no intention to expand, as do the AHK developers themselves. However, I still don't see this as a reason to use a Rust executable when you would require something like Wine to run AHK anyway (at which point you can just use the .bat with Wine too). 

Yeah that's one of the main issues that I wanted to tackle which is the compatability of AHK. A way I was thinking of doing this is by building a cross platform library or script that is able to interop with AHK through dll calls or other methods which would reduce or at least change the dependence on the windows api. Meaning that in the future it would be easier to make the scripts more cross platform

> I think that would be nice and would definitely make the installation process easier 😃

Ok, I would (as you probably would have guessed) like to make it using [tauri](https://tauri.app/) or [iced](https://iced.rs/) which are both good gui options with cross platform support made in rust. However I am not really set in a language or framework for a gui as I haven't done that much gui work (most of it has been in tauri though).

Also, what is your discord? I assume you are in the server just think it could be beneficial to talk it out over there :grinning:

**Comment by zspz** [comment]
There are plenty of cross-platform desktop automation libraries and software out there in a variety of languages (although in my opinion, none are close to the convenience and simplicity of AHK), it was just never in our interest to make this macro cross-platform at all.
I'm only active for a bit now because of the Christmas break, so I don't think my Discord will be of much use (nor do I answer DMs) but my username is `xspx`.

**Comment by supercoolspy** [comment]
UI Design currently
image

**Pull request closed without merging**
