### PR TITLE
[New Feature] Sticker Stacker

### PR DESCRIPTION
**Pull request by PewcioS**
Added:
Sticker Stacker option in the Collect tab, located below the HoneyStorm option.

Warning:
When the sticker option is enabled, a warning will be displayed.
image

Info:
Players will stack stickers every hour (max cooldown: 1 hour).
I only made cannon option movement, that means player can't use walk method.

Sticker Stacker Showcase: https://cdn.discordapp.com/attachments/833195624111407175/1196109374419128481/2024-01-14_16-06-31.mp4?ex=65b66ea9&is=65a3f9a9&hm=ec5ebfc08de7f86ce093d72f637f4a97b384be919d50b56fa9e9c303296c199a&

### CODE REVIEW

**Comment by PewcioS** [comment]
im testing this on rdp and it looks like there's an issue with Mouse movement its not going to correct place and because of that its not clicking stickers, and other buttons.

**Comment by misc-et** [comment]
Thanks for submitting this pull request! It looks great and is a feature that has been requested. 

A couple of thoughts, just in terms of user functionality:

This may be better thought of as a boost item rather than a collect item. The user is not technically collecting something, but loading/stacking a personal boost machine which grants a timed and extendable boost if the user either stacks a sticker or selects the option to activate with tickets. 

Therefore, it may fit better on the boost tab. It may also be important to include some features that other boost tasks have, such as options to:
- Select the preferred frequency of use (eg every X:XX minutes)
- Select the maximum number of stickers they’d like to donate (unique stickers are a finite item and users may want to save some for planned boosts etc)
- Use tickets rather than a sticker to activate the boost, e.g. during a Honeyday event

No need to act on this now, pending others' input, just noting for the discussion.

**Comment by PewcioS** [comment]
Thanks!

I only made base for it to work also i tried to make option to chose between tickets and stickers but its too complicated for me i literally never touched ahk or made my own script in the past, but its very similar to python, Lua.

Thats why i only made basic system to make it at least work, soo yea i don't have enought knowlage to add option such as selecting between stickers and tickets, i tried to make it yesterday just by looking at mondo script part with selecting kill,buff but i gave up its just too compleacated for me, same with preferred frequency of use.

Soo yea i was just cheacking out if i can make new function at my own, if theres any one that can do it that would be grate.

**Comment by zspz** [comment]
Hi, thanks for the PR, this looks great!
Two things:
- It looks like the encoding was changed from UTF-8-BOM to UTF-8, can you change this back?
- Can you rename the variable to `StickerStackerCheck` instead of `StickerStackerCheack`?

**Comment by PewcioS** [comment]
Alright, I changed the variable name to StickerStackerCheck. Also, I'm not sure where I can change the encoding. I tried to find any settings or tutorials for it, but I just can't.

**Comment by zspz** [comment]
It depends on the editor, in VS Code for example it is located on the bottom right:
image
The reason this is necessary can be found [here](https://www.autohotkey.com/docs/v2/FAQ.htm#nonascii).
I changed it for you in the latest commit.

I'm actually quite happy with this as an initial release, do you think it's ready?
The feature can always be built upon in future updates.

**Review by PewcioS — COMMENTED** [review]
alright

**Comment by zspz** [comment]
I fixed the coordinates and added a walk path.
If I have some time tomorrow, I may move this to Boost tab as @misc-et suggested, add a detection for the Stack Boost time, and add an option to use tickets as well as stickers.

**Comment by zspz** [comment]
All done, ready to merge 👍

**Pull request merged**
